### ISSUE TITLE
[BUG] 다른 플레이어 음성 ON/OFF 불가

### ISSUE THREAD

**Issue by spaff13** [boostcampwm-2022/web15-Teleparty#168]
## 버그 설명

다른 플레이어의 음량 조절 불가

## 재현 방법

플레이어 리스트의 마이크 버튼을 클릭한다.

## 의도된 동작

다른 플레이어의 음성을 끄면 소리가 나지 않고 켜면 소리가 나온다.

**Comment by jjiny0716** [comment]
https://github.com/boostcampwm-2022/web15-Teleparty/pull/207
